[package]
name = "htmx-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tera = "1"
serde = { version = "1.0", features = ["derive"] }
shuttle-actix-web = "0.46.0"
shuttle-runtime = "0.46.0"
shuttle-shared-db = { version = "0.46.0", features = ["postgres", "sqlx"] }
sqlx = "0.7.1"
